### ISSUE TITLE
vals?

### ISSUE THREAD

**Issue by sgnoohc** [aminnj/plottery#3]
What are these "vals" supposed to be?
https://github.com/aminnj/plottery/blob/master/plottery.py#L538

Is this a correct fix?
https://github.com/sgnoohc/plottery/commit/0955dd23fd7f19ab5a86eadc3ec72b2ee376edd8

**Comment by aminnj** [comment]
Yes, this is the correct fix, feel free to submit a PR so I can get the other feature you put in

**Comment by sgnoohc** [comment]
I obliterated my commit for that.
Could you fix it from your end?

**Comment by aminnj** [comment]
Done
