### ISSUE TITLE
yaxis_range does not work

### ISSUE THREAD

**Issue by sgnoohc** [aminnj/plottery#4]
yaxis_range is not working.
I believe for THStack the object that you're setting the "Ranges" are not the ones that are being drawn.
Afaik, you have to use https://root.cern.ch/doc/master/classTHStack.html#a18db0d7d4508cfe2fa0b030c4daa334d
after it has been drawn on some canvas, in order for that to actually return non-null result.

**Comment by sgnoohc** [comment]
So I hacked such that the axes style function will just overwrite "SetMaximum" based on the opt["yaxis_range"][1]. But... that screwed up other things.
The smart legend "ymax" values are not propagated based on yaxis_range hence, my hack did not get the ymax values correctly to the smart_legend.. which then screws up the yfrac... which then screws up the ycoord... and the smart legend gets squeezed in...

See below.. the X's are hovering way higher.

**Comment by aminnj** [comment]
Solved by https://github.com/aminnj/plottery/commit/b76c4dbac2c4b4f5227ae3f70996c6509106ad7d
