### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by sgnoohc** [aminnj/plottery#5]
I am going to start aggregating typos here.
https://github.com/aminnj/plottery/blob/master/plottery.py#L24 Boolean
https://github.com/aminnj/plottery/blob/master/plottery.py#L288 defalt

**Comment by aminnj** [comment]
Addressed by https://github.com/aminnj/plottery/commit/87b699add6b95bd0f5c8f7843325a61e534bdf19 and https://github.com/aminnj/plottery/commit/ba140cc9833abfa1f4aa589f3ced76b2f6080bb2
